@host = 127.0.0.1:8080

### 

# @name get_orders

GET /order/all HTTP/1.1
Host: {{host}}

### 訂單成功

# @name create_order

POST /order/create HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "userId": "1",
    "productId":"2"
}

### 訂單失敗，無此用戶

# @name create_order

POST /order/create HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "userId": "2001",
    "productId":"2"
}