server:
  port: 8080
spring.cloud.stream:
  # 提供多種binder設定
  binders:
    defultKafka:
      type: kafka
      environment:
        spring.kafka:
          bootstrap-servers: 172.20.101.27:9091
          producer:
            # 要等待Leader成功收到數據並且得到確認，才發送下一條訊息。
            acks: 1
          consumer:
            auto-offset-reset: earliest
            # 表示消費者會週期性自動提交消費offset
            enable-auto-commit: true
            # 自動提交的間隔
            auto-commit-interval: 100
  # functionName對應服務的Bean   
  function:
    definition: orderSupplier;paymentEventConsumer;inventoryEventConsumer
  # bindingName的命名規則
  # input :<functionName>-in-<index>
  # output:<functionName>-out-<index>
  bindings:
    orderSupplier-out-0:
      binder: defultKafka
      destination: order-event
    paymentEventConsumer-in-0:
      binder: defultKafka
      destination: payment-event
    inventoryEventConsumer-in-0:
      binder: defultKafka
      destination: inventory-event

